### ISSUE TITLE
Navbar formatting is weird

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/Jekyll-LLNL-Theme#14]
The current nav include is creating strangely formatted content (probably NOT what is intended):

![image](https://user-images.githubusercontent.com/828452/57985500-bde43280-7a1d-11e9-8463-389506755d0b.png)

**Comment by gonsie** [comment]
Yeah... when I created the remote theme we didn’t have the About pull down. The remote theme does automatically create entries in the nav bar, but I may have to rethink how that’s done with pull downs.

**Comment by gonsie** [comment]
the changes made in llnl/llnl.github.io#102 were not merged back to this theme.

**Comment by IanLee1521** [comment]
Also needed: 2a7a45c and 64626d6
