### ISSUE TITLE
sub-site assets

### ISSUE THREAD

**Issue by gonsie** [LLNL/Jekyll-LLNL-Theme#5]
assets are included through relative URLs ... which can break for project sites. Same issue dealt with in PR #4.

I'll PR a fix for this eventually.

**Comment by IanLee1521** [comment]
Let's go ahead and add these into the new cdn.llnl.gov that I've been building up. I can point you to that repo (it is internal).

**Comment by gonsie** [comment]
Is cdn.llnl.gov behind the firewall? I can't get to it right now from home.

**Comment by IanLee1521** [comment]
No, I was just able to get to it on my phone... maybe a minor glitch?
