### ISSUE TITLE
Convert to Gem based theme

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/Jekyll-LLNL-Theme#6]
Rather than all the content in a site that needs to be cloned as the starting point for a new site, let's instead make this a Gem based theme that we can reuse in various places:

https://jekyllrb.com/docs/themes/

**Comment by gonsie** [comment]
Great idea! The only issue is that GitHub pages only works with a select few gem-based themes (see [this page](https://pages.github.com/themes/)).

I've done this anyways... our documentation will have to be super clear about the usefulness of the gem.

**Comment by gonsie** [comment]
Yay!! You can now use any gem with GitHub pages :smile: https://github.com/blog/2464-use-any-theme-with-github-pages

I'm working making sure the gem works properly.
